// Generated by CoffeeScript 1.11.1
(function() {
  $(function() {
    var jankenhand;
    app.initialize();
    return jankenhand = ['rock', 'scissors', 'paper'];
  });

  window.app = {
    initialize: function() {
      this.setBind();
      this.pchand = null;
      this.myhand = null;
      this.life = 3;
      this.lifeDecrase = 1;
      return this.lifePc = 3;
    },
    setBind: function() {
      $('#rock').click((function(_this) {
        return function() {
          return _this.clickprocess('rock');
        };
      })(this));
      $('#scissors').click((function(_this) {
        return function() {
          return _this.clickprocess('scissors');
        };
      })(this));
      return $('#paper').click((function(_this) {
        return function() {
          return _this.clickprocess('paper');
        };
      })(this));
    },
    checklife: function() {
      if (this.life === 0 || this.lifePc === 0) {
        return this.showGameOver();
      }
    },
    showGameOver: function() {
      if (this.life === 0) {
        $('.overlay').css('visibility', 'visible');
        $('#lastmessage').html("あなたの負け");
        $('#lastpic').attr('src', 'img/lose.png');
        $('#replay-button').click((function(_this) {
          return function() {
            return _this.replay();
          };
        })(this));
        return $('#quit-button').click((function(_this) {
          return function() {
            return _this.closeApp;
          };
        })(this));
      } else {
        $('.overlay').css('visibility', 'visible');
        $('#lastmessage').html("あなたの勝ち");
        $('#lastpic').attr('src', 'img/win.png');
        $('#replay-button').click((function(_this) {
          return function() {
            return _this.replay();
          };
        })(this));
        return $('#quit-button').click((function(_this) {
          return function() {
            return _this.closeApp();
          };
        })(this));
      }
    },
    replay: function() {
      var num, results;
      console.log('replay');
      console.log(this.life);
      console.log(this.lifePc);
      this.life = 3;
      this.lifePc = 3;
      $('#result').html('じゃんけん...');
      $('.overlay').css('visibility', 'hidden');
      num = 1;
      results = [];
      while (num <= 3) {
        $("#myHeart" + num).css('visibility', 'visible');
        $("#pcHeart" + num).css('visibility', 'visible');
        results.push(num++);
      }
      return results;
    },
    closeApp: function() {
      console.log('close');
      return window.open('about:blank', '_self').close();
    },
    clickprocess: function(hand) {
      $('#picBoxMe').html($("<img class=\"pic\" src=\"img/" + hand + ".png\">"));
      $('.janken_picBox').css('border', 'none');
      this.randamHand();
      this.myhand = this.myhandConvertTonum(hand);
      return this.judge();
    },
    myhandConvertTonum: function(hand) {
      if (hand === 'rock') {
        return 0;
      } else if (hand === 'scissors') {
        return 1;
      } else {
        return 2;
      }
    },
    randamHand: function() {
      var jankenhand, pchand;
      jankenhand = ['rock', 'scissors', 'paper'];
      pchand = jankenhand[_.random(0, 2)];
      if (pchand === 'rock') {
        this.pchand = 0;
      } else if (pchand === 'scissors') {
        this.pchand = 1;
      } else {
        this.pchand = 2;
      }
      return $('#picBoxPc').html($("<img class=\"pic\" src=\"img/" + pchand + ".png\">"));
    },
    judge: function() {
      var hands;
      hands = this.myhand - this.pchand;
      if (this.pchand === this.myhand) {
        return $('#result').html('あいこ');
      } else if ((hands === -1) || (hands === 2)) {
        $('#result').html('勝ち');
        return this.heartremovePc();
      } else {
        $('#result').html('負け');
        return this.heartRemoveMe();
      }
    },
    heartRemoveMe: function() {
      $("#myHeart" + this.life).css('visibility', 'hidden');
      this.life = this.life - this.lifeDecrase;
      this.checklife();
      return console.log(this.life);
    },
    heartremovePc: function() {
      $("#pcHeart" + this.lifePc).css('visibility', 'hidden');
      this.lifePc = this.lifePc - this.lifeDecrase;
      this.checklife();
      return console.log(this.lifePc);
    }
  };

}).call(this);
